server:
  port: 47
spring:
  datasource:
    username: carblog
    password: carblog
    type: com.alibaba.druid.pool.DruidDataSource
    # 配置监控统计拦截的filters,去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.106.188.177:3306/carblog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    logSlowSql: true
    # 初始化
    initialSize: 3
    # 最大
    maxActive: 20
    # 最小
    minIdle: 3
    # 最大连接等待超时时间
    maxWait: 60000
    # 打开PSCache,并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 配置间隔多久才进行一次检测,检测需要关闭的空闲连接,单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间,单位是毫秒
    minEvictableIdleTimeMillis: 300000

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
  config: classpath:config/log4j2.xml
