server:
  port: 47
spring:
  profiles:
    active: dev

  jpa:
    hibernate:
      #自动建表
      ddl-auto: update
      #查看sql
      show-sql: true
      format_sql: true
      #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      show-sql: true
      format_sql: true
      #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  main:
    allow-bean-definition-overriding: true
  mvc:
    static-path-pattern: /**
logging:
  config: classpath:config/log4j2.xml
